version: '3.8'

services:
  db:
    image: postgres:16
    container_name: shorty-db
    environment:
      POSTGRES_USER: umair
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shorty
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: